title: OPDX Protocol Specification
description: Welcome to the specification of the Open Profile Data Exchange (OPDX) Protocol.
theme: just-the-docs

url: https://berrysauce.dev/justthedocs

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
